yearn/yearn-comms

Annoucements/The Blue Pill/The Blue Pill.md, Annoucements/What do I need to write a strategy/What do I need to write a strategy.md, Annoucements/yearn = yield function/Yearn = Yield Function.md, Articles/Medium/Wot is going on/Can Yearn Disrupt/Can Yearn Disrupt the 110 Trillion Asset Management Industry.md
testing a PR to Portuguese branch
=> Test pull request

Articles/Medium/Andre Cronje/Introducing Fixed Forex/Introducing Fixed Forex.md
=> Update Introducing Fixed Forex.md

Articles/Medium/Andre Cronje/Decentralized Payroll Management for DAOs/Decentralized Payroll Management for DAOs.md
=> Update Decentralized Payroll Management for DAOs.md

Articles/Medium/Andre Cronje/Introducing Fixed Forex/Introducing Fixed Forex.md
Translated AC's fixed forex article
=> Fixed Forex - Portuguese

Newsletters/Yearn Finance Newsletter #41/Yearn Finance Newsletter #41.md
if i understand correctly, line 72 was broken incorrectly into 74 by the automatic fetching tool
=> fixed duplicated/wrong line-break at line 72-74

Newsletters/Yearn Finance Newsletter #46/Yearn Finance Newsletter #46.md
=> Translation Portuguese

Articles/Medium/Wot is going on/Can Yearn Disrupt/Can Yearn Disrupt the 110 Trillion Asset Management Industry.md
=> Translation to Portuguese

Articles/Medium/Wot is going on/Yearn's Dai Vault/Yearn's Dai Vault.md
=> Yearn's dai Vault Translation

Articles/Medium/Yearn.Finance/Yearn UI v3/Yearn-UI-v3.md
=> Yearn v3 Translation

Articles/Medium/Yearn.Finance/Yearn UI v3/Yearn-UI-v3.md
I translated the medium article "Yearn UI v3.0" :)
thanks!
=> add Yearn UI v3.0

Articles/Medium/Yearn.Finance/Decentralized payroll management for DAOs/Decentralized payroll management for DAOs.md
=> translate(medium): coordinape

Newsletters/Yearn Finance Newsletter #47/Yearn Finance Newsletter #47.md
=> [CMT-31] YN 47

Annoucements/Token Terminal/Token Terminal.md
=> [CMT-48] - Token terminal

Newsletters/Yearn Finance Newsletter #47/Yearn Finance Newsletter #47.md
=> [CMT-29] Update Yearn Finance Newsletter #47.md

Newsletters/Yearn Finance Newsletter #47/Yearn Finance Newsletter #47.md
I translated Newsletter #47 :)
thanks!
=> [CMT-30] [Japanese] Yearn Finance Newsletter #47.md

Articles/Medium/Yearn.Finance/yvBOOST/thats-boost-folks.md
=> [CMT-57] - yvBOOST

Newsletters/Yearn Finance Newsletter #48/Yearn Finance Newsletter #48.md
=> [CMT-61] - YN48

pages/categories.md
I translated categories page. thanks!
=> [Japanese] Add categories

Annoucements/_posts/Deposit-Together/2021-11-01-Deposit-Together.md
translation(announcement): Deposit-Together in french by Cryptouf
=> translation(announcement): Deposit-Together

Financials/_posts/Quarterly-Report/2021-Q2/2021-09-11-2021-Q2.md
=> Update 2021-09-11-2021-Q2.md [CMT-36]

Tweets/_posts/Yearn grant Atlantis World/2021-08-31-Yearn-grant-Atlantis-World.md
=> Revert "[CMT-395] Tweet - Atlantis World Grant #539 German"

Articles/_posts/Argent/2021-08-24-easily-earn-with-yearn-v2-in-argent.md
=> [CMT-79] - Easily earn with Yearn v2 in Argent

Articles/_posts/SEBA Bank/Yearn-Finance-Decentralised-Asset-Management/2021-06-02-Yearn-Finance-Decentralised-Asset-Management.md
=> [CMT-157] - Yearn Finance - Dec Asset Management

Tweets/_posts/Claim from old ygov/2021-07-10-Claim-from-old-ygov.md
=> [CMT-366] - Claim from old yGov

Articles/_posts/The Blue Pill/The Blue Pill.txt
=> [CMT-190] - Article - The Blue Pill

Tweets/_posts/What is Yearn/2021-10-09-What-is-Yearn.md
=> [CMT-432] - Tweet - What is Yearn?

Tweets/_posts/Transparency Summary/2021-10-05-TransparencySummary.md
=> [CMT-421] - Tweet - Transparency Summary

Annoucements/_posts/Yearn & Synthetix DAO twitter space/2021-07-29-Yearn-&-Synthetix-DAO-twitter-space.md
=> [CMT-283] - Yearn & Synthetix DAO twitter space

Annoucements/_posts/What do I need to write a strategy/2021-07-21-What-do-I-need-to-write-a-strategy.md
=> [CMT-272] - What do I need to write a strategy?

Tweets/_posts/Bear market, bullish development/2021-07-22-Bear-market,-bullish-development.md
=> [CMT-377] - Bear Market

Annoucements/_posts/Updated YFIStats Dashboards/2021-09-30-Updated-YFIStats-Dashboards.md
=> [CMT-338] - YFI Stats

Tweets/_posts/Bowswap.finance/2021-09-10-bowswapfinance.md
=> [CMT-410] - Bowswap

Annoucements/_posts/Update Bowswap.Finance/2021-08-26-Update-Bowswap.Finance.md
=> [CMT-327] - Bowswap

Annoucements/_posts/The Blue Pill Release/2021-08-03-Blue-Pill-Release.md
=> [CMT-316] - The blue Pill

Tweets/_posts/What is Yearn/2021-10-09-What-is-Yearn.md
[CMT-427] Tweet - What is Yearn? #566 [French]  by Cryptouf
=> [CMT-427] Tweet - What is Yearn? #566 [French]

Annoucements/_posts/Zero Knowledge Podcast/2021-05-05-Zero-Knowledge-Podcast.md
=> [CMT-250] - Announcements - Zero Knowledge Podcast

Tweets/_posts/What is a DAO/2021-06-30-What-is-a-DAO.md
=> chore(what is a dao): update header metadata

Tweets/_posts/What is a DAO/2021-06-30-What-is-a-DAO.md
=> [CMT-355] - DAO

Tweets/_posts/Risk, Tooling, & Insight/2021-08-12-Risk,-Tooling,-&-Insight.md
=> [CMT-388] - Risks, Tooling and Insight

Tweets/_posts/What is Yearn/2021-10-09-What-is-Yearn.md
I translated about yearn, thanks!
=> [CMT-431] translation(tweet): what is yearn

Tweets/_posts/Yearn grant Atlantis World/2021-08-31-Yearn-grant-Atlantis-World.md
=> [CMT-399] - Atlantis World

Tweets/_posts/Transparency Summary/2021-10-05-TransparencySummary.md
I translated about yearn, thanks!
=> [CMT-420] translation(tweet): what is yearn

Tweets/_posts/Bowswap.finance/2021-09-10-bowswapfinance.md
I translated about bowswap. thanks!
=> [CMT-409] translation(tweet): bowswap

Tweets/_posts/Bear market, bullish development/2021-07-22-Bear-market,-bullish-development.md
[CMT-372] Tweet - Bear market, bullish development #518 FRENCH by Cryptouf
=> [CMT-372] Tweet - Bear market, bullish development #518 FRENCH

Annoucements/_posts/Legal-Activism-DAO/2021-08-03-Legal-Activism-DAO.md, Annoucements/_posts/The Blue Pill Ann/2021-07-30-The-Blue-Pill-Ann.md, Tweets/_posts/Bowswap.finance/2021-09-10-bowswapfinance.md, Tweets/_posts/Claim from old ygov/2021-07-10-Claim-from-old-ygov.md
translation(tweet): Claim from old ygov [french] by Cryptouf
=> translation(tweet): Claim from old ygov [french] 

Articles/_posts/Forum/How we think about Yearn/2020-10-20-How-we-think-about-Yearn.md
I translated about how we think about yearn, thanks!
=> [CMT-89] translation(forum): how we think about yearn

Articles/_posts/Medium/Andre Cronje/Introducing Fixed Forex/2021-07-02-Introducing-Fixed-Forex.md
I translated about Fixed Forex, thanks!
=> [CMT-167] translation(medium): introduce Fixed Forex

Articles/_posts/Argent/2021-08-24-easily-earn-with-yearn-v2-in-argent.md
I translated about argent, thanks!
=> [CMT-78] translation(article): easily earn with yearn v2 in argent

Tweets/_posts/Claim from old ygov/2021-07-10-Claim-from-old-ygov.md
I translated about claim from old yGov, thanks!
=> [CMT-365] translation(tweet): claim from old yGov

Tweets/_posts/Risk, Tooling, & Insight/2021-08-12-Risk,-Tooling,-&-Insight.md
I translated about risk and tooling and insight, thanks!
=> [CMT-387] translation(tweet): risk, tooling, & insignt

Newsletters/_posts/Yearn-Finance-Newsletter-49/2021-11-14-Yearn-Finance-Newsletter-49.md
I translated about newsletter, thanks!
=> translation(newsletter): Newsletter49 [japanese]

Newsletters/_posts/Yearn-Finance-Newsletter-43/2021-08-11-Yearn-Finance-Newsletter-43.md
Yearn Finance Newsletter #43 - Greek Translation
=> Yearn Finance Newsletter #43 - Greek Translation

Newsletters/_posts/Yearn-Finance-Newsletter-49/2021-11-14-Yearn-Finance-Newsletter-49.md
I fixed the unnatural part, sorry > <
=> fix: my updates

Newsletters/_posts/Yearn-Finance-Newsletter-49/2021-11-14-Yearn-Finance-Newsletter-49.md
translation(newsletter): 49 [French] .
Cancelled the previous one and made this one. I was not sure i did it properly
=> translation(newsletter): 49 [French]

Annoucements/_posts/Legal-Activism-DAO/2021-08-03-Legal-Activism-DAO.md
=> [CMT-305] -  Prop Fund Builder First Legal Act DAO

Newsletters/_posts/Yearn-Finance-Newsletter-49/2021-11-14-Yearn-Finance-Newsletter-49.md
=> [CMT-443] - Yearn Weekly Newsletter #49

Annoucements/_posts/Updated YFIStats Dashboards/2021-09-30-Updated-YFIStats-Dashboards.md
I try to insert my name Nesyeth under translator in the header but the format changes.
=> [CMT-334] Ann - YFIStats Dashboards #485 German

.github/workflows/auto-close-fixed-issues.yml
This pull request is for testing the PR issue close merge fix
Fixes #699
N/A
=> chore: testing pr issue close

.github/workflows/auto-close-fixed-issues.yml
This pull request is a test
Fixes #714
N/A
=> test: testing pr auto close of issue

.github/workflows/greetings.yml
This send an automated reply to a first time user who makes an issue or PR to this repo, telling them about our onboarding forum and discord channel where they can reach us for more info.
=> feat: add first time user greeting

.github/workflows/auto-close-fixed-issues.yml
This pull request ... fixes auto close
Fixes #717 
=> fix: auto close fixed issues

.github/ISSUE_TEMPLATE/article_request.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/auto-close-fixed-issues.yml
This pull request add issue templates for bug reports and asking for articles to be added to the blog
Fixes #723
=> [CMT-454-724] Add issue template

Tweets/_posts/Risk, Tooling, & Insight/2021-08-12-Risk,-Tooling,-&-Insight.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #535
=> [CMT-452-722] Risk, Tooling, & Insight

Tweets/_posts/Bear market, bullish development/2021-07-22-Bear-market,-bullish-development.md
=> [CMT-378] Update to Bear-market,-bullish-development.md

Newsletters/_posts/Yearn-Finance-Newsletter-48/2021-10-10-Yearn-Finance-Newsletter-48.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #290 
=> [CMT-459-732] Yearn Finance NL 48 - Greek Translation

Newsletters/_posts/Yearn-Finance-Newsletter-49/2021-11-14-Yearn-Finance-Newsletter-49.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-458-731] Yearn finance newsletter 49 - Greek translation [CMT-440]

Tweets/_posts/Bowswap.finance/2021-09-10-bowswapfinance.md
=> [CMT-328] Update 2021-09-10-bowswapfinance.md

Tweets/_posts/What is a DAO/2021-06-30-What-is-a-DAO.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-456-727] What is a DAO

Tweets/_posts/What is a DAO/2021-06-30-What-is-a-DAO.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-457-729] Update 2021-06-30-What-is-a-DAO.md

Tweets/_posts/What is a DAO/2021-06-30-What-is-a-DAO.md
>```
>fix #1 #2 #3
>```
Fixes #505 
=> [CMT-357] Tweet - What is a DAO?

Articles/_posts/Forum/What can you do with YFI/2021-05-05-What-can-you-do-with-YFI.md
This pull request is for forum what can u do with YFI article
close #340
=> [CMT-137] Article - What can you do with YFI?

Articles/_posts/Medium/Yearn State of the Vaults/The Vaults at Yearn/2021-11-05-The-Vaults-at-Yearn.md
Add Vi L10n for The Vaults at Yearn (2021-11-05)
Fixes #412 
- [x ] Add a new translation
=> [CMT-237] Article - The Vaults at Yearn (2021-11-05)

Newsletters/_posts/Yearn-Finance-Newsletter-49/2021-11-14-Yearn-Finance-Newsletter-49.md
This pull request tranlsates yn 49
Fixes #795
=> [CMT-460-740] Update 2021-11-14-Yearn-Finance-Newsletter-49.md RM3

Newsletters/_posts/Yearn-Finance-Newsletter-44/2021-09-02-Yearn-Finance-Newsletter-44.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-464-748] Yearn Finance NL #44 Greek translation

Newsletters/_posts/Yearn-Finance-Newsletter-45/2021-09-07-Yearn-Finance-Newsletter-45.md
This pull request contains the Yearn Finance Newsletter #45 Greek Translation.
=> [CMT-465-749] Yearn Finance Newsletter #45 Greek Translation

Newsletters/_posts/Yearn-Finance-Newsletter-46/2021-09-12-Yearn-Finance-Newsletter-46.md
This pull request adds a new translation (Greek) for NL #46
Fixes #(issue)
=> [CMT-466-750] Yearn Finance NL #46 Greek translation

Newsletters/_posts/Yearn-Finance-Newsletter-47/2021-09-26-Yearn-Finance-Newsletter-47.md
Adds a new translation for NL 47
Fixes #492 
=> [CMT-467-751] Yearn Finance NL #47 Greek Translation

Annoucements/_posts/What do I need to write a strategy/2021-07-21-What-do-I-need-to-write-a-strategy.md
translation( Annoucements): What do I need to write a strategy [FRENCH] by cryptouf
fixes #431
=> translation( Annoucements): What do I need to write a strategy [FRENCH]

Tweets/_posts/Transparency Summary/2021-10-05-TransparencySummary.md
translation [CMT-416] Tweet - Transparency Summary Fixes #556 in [french] by cryptouf
=> [CMT-416] Tweet - Transparency Summary #556 [french]

Articles/_posts/Medium/Yearn.Finance/The Blue Pill/2021-07-29-The-Blue-Pill.md
>```
>fix #1 #2 #3
>```
Fixes #384 
=> [CMT-192] Article - The Blue Pill

Articles/_posts/The Blue Pill/The Blue Pill.txt
This pull request is translated the blue pills to Japanese
Fixes #381 
https://thebluepill.eth.link/
=> [CMT-189]Update The Blue Pill.txt

Articles/_posts/Forum/What can you do with YFI/2021-05-05-What-can-you-do-with-YFI.md
>```
>fix #1 #2 #3
>```
Fixes #333 
=> [CMT-129] translate what can you do with YFI to Chinese

Annoucements/_posts/Token Terminal/2021-09-03-Token-Terminal.md
translation Announcements - Token Terminal in [FRENCH] by Cryptouf
translation Announcements - Token Terminal in [FRENCH] by Cryptouf
=> Announcements - Token Terminal [FRENCH]

Articles/_posts/Medium/Wot Is Goin On/Yearn's Dai Vault/2021-06-01-Yearn's-Dai-Vault.md
>```
>fix #1 #2 #3
>```
Fixes #349
=> [CMT-148] Article - Yearn's Dai Vault

Articles/_posts/Medium/Andre Cronje/Fair launches, decentralized collaboration, and Fixed Forex/2021-07-21-Fair-launches-decentralized-collaboration-and-Fixed-Forex.md
>```
>fix #1 #2 #3
>```
Fixes #363 
=> [CMT-175]  German translation

Annoucements/_posts/Deposit-Together/2021-11-01-Deposit-Together.md
>```
>fix #1 #2 #3
>```
Fixes #(issue)
=> Update 2021-11-01-Deposit-Together.md - RM3

Articles/_posts/Medium/Andre Cronje/Decentralized Payroll Management for DAOs/2021-03-31-Decentralized-Payroll-Management-for-DAOs.md
i translated the article about coordinape
Fixes #356 
- [✅] Add a new translation
=> [CMT-112] translation(article):Decentralized-Payroll-Management-for-DAOs

Articles/_posts/Forum/What can you do with YFI/2021-05-05-What-can-you-do-with-YFI.md
>```
>fix #1 #2 #3
>```
Fixes #(issue)
=> Update 2021-05-05-What-can-you-do-with-YFI.md RM3

Tweets/_posts/Transparency Summary/2021-10-05-TransparencySummary.md
The title was still in English. Fixed it
=> [CMT-498-799] new tittle

Newsletters/_posts/Yearn-Finance-Newsletter-50/2021-12-05-Yearn-Finance-Newsletter-50.md, Newsletters/_posts/Yearn-Finance-Newsletter-51/2021-12-22-Yearn-Finance-Newsletter-51.md, Newsletters/_posts/Yearn-Finance-Newsletter-52/2022-01-02-Yearn-Finance-Newsletter-52.md
Translation of the newsletter n'52 in French
This pull request is a translation in french of the last NL
- [X ] Add a new translation
=> [Newsletter] Newsletter 52- 51 and 50 [French]

Tweets/_posts/What is Yearn/2021-10-09-What-is-Yearn.md
>```
>fix #1 #2 #3
>```
Fixes #(issue)
=> 2021-10-09-What-is-Yearn - Hindi Translation

_includes/postbox.html, _sass/bootstrap/utilities/_borders.scss, assets/css/theme.scss, index.html
The current grid has a lot of white space between multiple blog post because of the grid taking the maximal height of the 3 items in the row.\
Fix this with this PR. Add some CSS style and some JS to correctly update the masonry
Add a masonry grid
Just a proposal, do whatever you want with it !\
*N/A*
=> [CMT-511-813] FRP: Update the grid for better flow

README.md, _config.docker.yml, _config.yml, docker-compose.yml
This pull request adds docker for easier deployment locally
=> [CMT-510-812] Add docker for easier deployment locally

Newsletters/_posts/Yearn-Finance-Newsletter-51/2021-12-22-Yearn-Finance-Newsletter-51.md
Portuguese Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-518-821] Update 2021-12-22-Yearn-Finance-Newsletter-51.md

Newsletters/_posts/Yearn-Finance-Newsletter-50/2021-12-05-Yearn-Finance-Newsletter-50.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-507-809] fixed line 63

Articles/_posts/Medium/Yearn.Finance/The Blue Pill/2021-07-29-The-Blue-Pill.md
>```
>fix #1 #2 #3
>```
Fixes #378 
=> [CMT-186] Article - The Blue Pill #378 German Translation

Newsletters/_posts/Yearn-Finance-Newsletter-52/2022-01-02-Yearn-Finance-Newsletter-52.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-540-846] YN #52 German Translation

Newsletters/_posts/Yearn-Finance-Newsletter-53/2022-01-11-Yearn-Finance-Newsletter-53.md
This pull request add Vi L10n for YN 53
Fixes #
=> [CMT-550-858] add vi l10 yn 53

Newsletters/_posts/Yearn-Finance-Newsletter-52/2022-01-02-Yearn-Finance-Newsletter-52.md
This pull request add Vi L10n for YN 52
Fixes #
=> [CMT-549-857] add vi l10n yn 52

Newsletters/_posts/Yearn-Finance-Newsletter-52/2022-01-02-Yearn-Finance-Newsletter-52.md
Portuguese translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-526-829] Update 2022-01-02-Yearn-Finance-Newsletter-52.md

Tweets/_posts/Why is Yearn Finance Built Different/2022-01-01-Why-is-Yearn-Finance-Built-Different.md
portuguese translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-564-872] Update 2022-01-01-Why-is-Yearn-Finance-Built-Different.md

Newsletters/_posts/Yearn-Finance-Newsletter-53/2022-01-11-Yearn-Finance-Newsletter-53.md
Hindi Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-562-870] Yearn Finance Newsletter #53 - Hindi

Newsletters/_posts/Yearn-Finance-Newsletter-52/2022-01-02-Yearn-Finance-Newsletter-52.md
Hindi Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-561-869] Yearn Finance Newsletter #52 - Hindi

Newsletters/_posts/Yearn-Finance-Newsletter-53/2022-01-11-Yearn-Finance-Newsletter-53.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-552-860] Update 2022-01-11-Yearn-Finance-Newsletter-53.md RM3

Newsletters/_posts/Yearn-Finance-Newsletter-50/2021-12-05-Yearn-Finance-Newsletter-50.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-558-866] Update 2021-12-05-Yearn-Finance-Newsletter-50.md- Greek

Newsletters/_posts/Yearn-Finance-Newsletter-52/2022-01-02-Yearn-Finance-Newsletter-52.md
=> [CMT-565-873] translation(newsletter): 52

Newsletters/_posts/Yearn-Finance-Newsletter-51/2021-12-22-Yearn-Finance-Newsletter-51.md
Hindi translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-556-864] Yearn Finance Newsletter #51 - Hindi

Newsletters/_posts/Yearn-Finance-Newsletter-53/2022-01-11-Yearn-Finance-Newsletter-53.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-555-863] Yearn Finance Newsletter #53 German Translation

Newsletters/_posts/Yearn-Finance-Newsletter-53/2022-01-11-Yearn-Finance-Newsletter-53.md
I translated Yearn Finance Newsletter #53 into japanese
new translate
=> [CMT-551-859] translation(newsletter): Yearn Finance Newsletter #53

Newsletters/_posts/Yearn-Finance-Newsletter-50/2021-12-05-Yearn-Finance-Newsletter-50.md
This pull request add Vi L10n for YN 50
Fixes #CMT-480
=> [CMT-547-855] CMT-480 vi L10n YN 50

Newsletters/_posts/Yearn-Finance-Newsletter-52/2022-01-02-Yearn-Finance-Newsletter-52.md
>```
>fix #1 #2 #3
>```
Fixes #(issue)
=>  Yearn-Finance-Newsletter-52 - TR

Articles/_posts/Medium/Andre Cronje/Decentralized Payroll Management for DAOs/2021-03-31-Decentralized-Payroll-Management-for-DAOs.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #321
=> [CMT-545-852] Update 2021-03-31-Decentralized-Payroll-Management-for-DAOs.md RM3

Newsletters/_posts/Yearn-Finance-Newsletter-51/2021-12-22-Yearn-Finance-Newsletter-51.md
This pull request add Vi L10n for YN 51
Fixes #
=> [CMT-567-875] re-add vi l10n yn 51

Newsletters/_posts/Yearn-Finance-Newsletter-51/2021-12-22-Yearn-Finance-Newsletter-51.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-524-827] Yearn-Finance-Newsletter-51- TR

Newsletters/_posts/Yearn-Finance-Newsletter-55/2022-01-26-Yearn-Finance-Newsletter-55.md
[Newsletter] TRranslation in French NL55
[Newsletter] TRranslation in French NL55 
- [ X] Add a new translation
=> [Newsletter] TRranslation in French NL55

Newsletters/_posts/Yearn-Finance-Newsletter-54/2022-01-20-Yearn-Finance-Newsletter-54.md
This pull request add Vi L10n for YN 54
Fixes #
=> [CMT-613-922] add vi l10n yn54

Newsletters/_posts/Yearn-Finance-Newsletter-55/2022-01-26-Yearn-Finance-Newsletter-55.md
This pull request add Vi L10n for YN 55
Fixes #
=> [CMT-640-966] add vi l10n yn 55

Newsletters/_posts/Yearn-Finance-Newsletter-55/2022-01-26-Yearn-Finance-Newsletter-55.md
>```
>fix #1 #2 #3
>```
Fixes #(issue)
=> Yearn-Finance-Newsletter-55 - TR

Newsletters/_posts/Yearn-Finance-Newsletter-54/2022-01-20-Yearn-Finance-Newsletter-54.md
I translated newsletter #54
>```
>fix #1 #2 #3
>```
- [・] Add a new translation
=> translation(newsletter) : Yearn Finance newsletter #54

Articles/_posts/Medium/Yearn State of the Vaults/The Vaults at Yearn/2021-11-05-The-Vaults-at-Yearn.md
New Hindi translation PR with link fixes
=> [CMT-645-971] Update 2021-11-05-The-Vaults-at-Yearn.md

Newsletters/_posts/Yearn-Finance-Newsletter-56/2022-02-02-Yearn-Finance-Newsletter-56.md
translation Newsletter 56 in french
=> [Newsletter] n'56 translation [FRENCH]

Newsletters/_posts/Yearn-Finance-Newsletter-56/2022-02-02-Yearn-Finance-Newsletter-56.md
Sorry i made a mistake
Fixes #(issue)
=> [CMT-652-983] Update images

Articles/_posts/Medium/Wot Is Goin On/Yearn's Dai Vault/2021-06-01-Yearn's-Dai-Vault.md
=> [CMT-656-988] Update 2021-06-01-Yearn's-Dai-Vault.md - Spanish - RM3

Articles/_posts/SEBA Bank/Yearn-Finance-Decentralised-Asset-Management/2021-06-02-Yearn-Finance-Decentralised-Asset-Management.md
…ation
>```
>fix #1 #2 #3
>```
Fixes #353
=> [CMT-153] Article - Yearn Finance - Decentralised Asset - German 

Newsletters/_posts/Yearn-Finance-Newsletter-55/2022-01-26-Yearn-Finance-Newsletter-55.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-655-986] Yearn Finance Newsletter #55 German translation

Articles/_posts/Medium/Wot Is Goin On/Can Yearn Disrupt/2021-04-07-Can-Yearn-Disrupt-the-110-Trillion-Asset-Management-Industry.md
…-Industry.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #330
=> [CMT-651-981] Update 2021-04-07-Can-Yearn-Disrupt-the-110-Trillion-Asset-Management…Spanish RM3

Newsletters/_posts/Yearn-Finance-Newsletter-55/2022-01-26-Yearn-Finance-Newsletter-55.md
This pull request is translated newsletter #55 into Japanese
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-650-980] translation(newsletter): Yearn Finance Newsletter #55

Newsletters/_posts/Yearn-Finance-Newsletter-55/2022-01-26-Yearn-Finance-Newsletter-55.md
portuguese translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-646-972] Update 2022-01-26-Yearn-Finance-Newsletter-55.md

Newsletters/_posts/Yearn-Finance-Newsletter-55/2022-01-26-Yearn-Finance-Newsletter-55.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-639-965] Yearn finance newsletter 55

Newsletters/_posts/Yearn-Finance-Newsletter-55/2022-01-26-Yearn-Finance-Newsletter-55.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-618-944] Update 2022-01-26-Yearn-Finance-Newsletter-55.md Spanish - RM3

Newsletters/_posts/Yearn-Finance-Newsletter-54/2022-01-20-Yearn-Finance-Newsletter-54.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-610-919] Update 2022-01-20-Yearn-Finance-Newsletter-54.md Spanish RM3

public/_posts/_newsletters/Yearn-Finance-Newsletter-46/pt.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-56/pt.md
Portuguese translation of NL#56
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-663-997] Newsletter 55 (translation - pt)

public/_posts/_newsletters/Yearn-Finance-Newsletter-54/en.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-54/fr.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-54/pt.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-54/vi.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-54/zh.md
Portuguese translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-667-1002] Add old translation: YN 54 - pt

public/_posts/_newsletters/Yearn-Finance-Newsletter-50/pt.md
Portuguese Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-668-1003] translation(newsletter): old 50 - pt

public/_posts/_newsletters/Yearn-Finance-Newsletter-57/fr.md
add french translation for Newsletter 57
=> [NEWSLETTER] 57 in French

public/_posts/_newsletters/Yearn-Finance-Newsletter-57/fr.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-57/pt.md
=> [CMT-676-1013] translation(newsletter): 57 - pt - jk

public/_posts/_newsletters/Yearn-Finance-Newsletter-56/zh.md
=> [CMT-674-1011] Translated YN 56 to Chinese

public/_posts/_newsletters/Yearn-Finance-Newsletter-57/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-673-1010] Newsletter 57 - Create es.md - RM3

public/_posts/_podcasts/podcasts-talks/en.md
This pull request add new Yearn talks
Fixes #(issue)
=> [CMT-680-1017] add(podcasts): new talks

localization/es.json
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-682-1019] Update es.json- Spanish - RM3

public/_posts/_newsletters/Yearn-Finance-Newsletter-56/ja.md
This pull request is translate yearn newsletter #56 into japanese
Fixes #(issue)
=> [CMT-694-1032] translation(newsletter): Yearn newsletter #56

public/_posts/_articles/marco-worms/how-yearn-calculates-estimated-returns/fr.md
add French version  how-yearn-calculates-estimated-returns
=> [Article] add French version  how-yearn-calculates-estimated-returns

public/_posts/_articles/marco-worms/how-yearn-calculates-estimated-returns/en.md
=> [CMT-695-1033] small corrections

public/_posts/_articles/marco-worms/diving-into-yearn-metrics/fr.md
[Article] add French version  Diving-into-yearn-metrics
Fixes #(issue)
=> [Article] add French version  Diving-into-yearn-metrics

public/_posts/_newsletters/Yearn-Finance-Newsletter-49/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-717-1058] Update tr.md

public/_posts/_newsletters/Yearn-Finance-Newsletter-41/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-709-1050] Update tr.md

public/_posts/_newsletters/Yearn-Finance-Newsletter-42/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-710-1051] Update tr.md

public/_posts/_newsletters/Yearn-Finance-Newsletter-44/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-712-1053] Update tr.md

public/_posts/_newsletters/Yearn-Finance-Newsletter-45/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-713-1054] Update tr.md

public/_posts/_newsletters/Yearn-Finance-Newsletter-46/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-714-1055] Update tr.md

public/_posts/_newsletters/Yearn-Finance-Newsletter-47/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-715-1056] Update tr.md

public/_posts/_newsletters/Yearn-Finance-Newsletter-48/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-716-1057] Update tr.md

public/_posts/_newsletters/Yearn-Finance-Newsletter-50/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-718-1059] Update tr.md

public/_posts/_newsletters/Yearn-Finance-Newsletter-51/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-719-1060] Update tr.md

public/_posts/_newsletters/Yearn-Finance-Newsletter-52/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-720-1061] Update tr.md

public/_posts/_newsletters/Yearn-Finance-Newsletter-55/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-721-1062] Update tr.md

public/_posts/_newsletters/Yearn-Finance-Newsletter-56/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-722-1063] Update tr.md

public/_posts/_newsletters/Yearn-Finance-Newsletter-53/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-705-1046] tr.md

public/_posts/_newsletters/Yearn-Finance-Newsletter-54/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-706-1047] tr.md

public/_posts/_articles/marco-worms/diving-into-yearn-metrics/es.md
This pull request translates "Diving into Yearn Metrics" into SPANISH
=> [CMT-690-1027] translate(article): "Diving into Yearn Metrics" - ES

public/_posts/_articles/gemini/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-735-1077] translations(article): defi money robots - es

public/_posts/_newsletters/Yearn-Finance-Newsletter-51/es.md
This pull request translates "Yearn-Finance-Newsletter-51" into SPANISH
=> [CMT-733-1075] translate(newsletter): "Yearn-Finance-Newsletter-51" - ES

public/_posts/_newsletters/Yearn-Finance-Newsletter-52/es.md
This pull request translates "Yearn-Finance-Newsletter-52" into SPANISH
=> [CMT-732-1074] translate(newsletter): "Yearn-Finance-Newsletter-52" - ES

public/_posts/_articles/argent/es.md
This pull request translates "Easily earn with Yearn v2 in Argent" article into SPANISH
=> [CMT-731-1073] translate(article): "Easily earn with Yearn v2 in Argent" - ES

public/_posts/_newsletters/Yearn-Finance-Newsletter-52/de.md
This pull request translates "Yearn-Finance-Newsletter-52" into GERMAN
Fixes #0000
=> [CMT-739-1081] translate(newsletter): "Yearn-Finance-Newsletter-52" - DE

public/_posts/_newsletters/Yearn-Finance-Newsletter-51/de.md
This pull request translates "Yearn-Finance-Newsletter-51" into GERMAN
Fixes #0000
=> [CMT-738-1080] translate(newsletter): "Yearn-Finance-Newsletter-51" - DE

public/_posts/_articles/marco-worms/how-new-yearn-vault-strategies-are-endorsed/es.md
This pull request translates "How New Yearn Vault Strategies are Endorsed" into SPANISH
Fixes #0000
=> [CMT-691-1028] translate(article): "How New Yearn Vault Strategies are Endorsed" - ES

public/_posts/_articles/andre-cronje/liquidity-mining-rewards-v2/es.md
This pull request translates "Liquidity Mining Rewards v2" article into SPANISH
Fixes #0000
=> [CMT-726-1068] translate(article): "Liquidity Mining Rewards v2" - ES

public/_posts/_articles/andre-cronje/introducing-fixed-forex/es.md
This pull request translates "Introducing Fixed Forex" article into SPANISH
Fixes #0000
=> [CMT-728-1070] translate(article): "Introducing Fixed Forex" - ES

public/_posts/_articles/andre-cronje/fair-launches-decentralized-collaboration-and-fixed-forex/es.md
This pull request translates "Fair launches, decentralized collaboration, and Fixed Forex" article into SPANISH
Fixes #0000
=> [CMT-729-1071] translate(article): "Fair launches, decentralized collaboration, and Fixed Forex" - ES

public/_posts/_articles/yearn-finance/tenderly/es.md
This pull request translates "Yearn Finance Partners with Tenderly " into SPANISH
Fixes #(issue)
=> [CMT-742-1086] translate(article): "Yearn Finance Partners with Tenderly "- ES

public/_posts/_tweets/what-can-you-do-in-a-DAO/tr.md
This pull request translates "What-can-you-do-in-a-DAO" tweet into TURKISH
Fixes #(issue)
=> [CMT-707-1048] translate(tweet): "What-can-you-do-in-a-DAO" - TR

public/_posts/_articles/wot-is-goin-on/can-yearn-disrupt/tr.md
This pull request translates "Can-Yearn-Disrupt" article into TURKISH
Fixes #(issue)
=> [CMT-703-1042] translate(article): "Can-Yearn-Disrupt" - TR

public/_posts/_articles/gemini/tr.md
This pull request translates "Yearn Finance and Money Robots" article into TURKISH
Fixes #1043
=> [CMT-704-1043] translate(article): "Yearn Finance and Money Robots" - TR

public/_posts/_articles/yearn-finance/tenderly/fr.md
This pull request translates "Yearn Finance Partners with Tenderly" article into FRENCH
Fixes #(issue)
=> translate(article): "Yearn Finance Partners with Tenderly" - FR

public/_posts/_articles/forum/what-can-you-do-with-yfi/tr.md
This pull request translates "What-can-you-do-with-YFI" article into TURKISH
Fixes #0000
=> [CMT-701-1040] translate(article): "What-can-you-do-with-YFI" - TR

public/_posts/_newsletters/Yearn-Finance-Newsletter-57/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-704-1041] translate(newsletter): "Yearn-Finance-Newsletter-57" - TR

public/_posts/_announcements/deposit-together/tr.md
This pull request translates "Deposit Together" into TURKISH
Fixes #(issue)
=> [CMT-704-1045] translate(announcement): "Deposit Together" - TR

public/_posts/_articles/marco-worms/how-yearn-calculates-estimated-returns/pt.md
This pull request translates "How Yearn calculates estimated returns (APY)" article into PORTUGUESE
Fixes #0000
=> [CMT-687-1024] translate(article): "How Yearn calculates estimated returns (APY)" - PT

public/_posts/_newsletters/Yearn-Finance-Newsletter-50/de.md
This pull request translates "Yearn-Finance-Newsletter-50" into GERMAN
Fixes #0000
=> [CMT-723-1064] translate(newsletter): "Yearn-Finance-Newsletter-50" - DE

public/_posts/_articles/marco-worms/how-new-yearn-vault-strategies-are-endorsed/pt.md
This pull request translates "How new Yearn Vault strategies are endorsed" article into PORTUGUESE
Fixes #(issue)
=> [CMT-679-1016] translate(article): "How new Yearn Vault strategies are endorsed" - PT

public/_posts/_articles/forum/how-we-think-about-yearn/es.md
This pull request translates "How we think about Yearn" article into SPANISH
=> [CMT-730-1072] translate(article): "How we think about Yearn" - ES

public/_posts/_podcasts/podcasts-talks/tr.md
This pull request translates (podcast): "List of Podcasts and Talks" to Turkish
Fixes #(issue)
=> [CMT-756-1101] translate(podcast): "List of Podcasts and Talks" - TR

public/_posts/_articles/marco-worms/how-yearn-calculates-estimated-returns/tr.md
This pull request is about translated how-yearn-calculates-estimated-returns to Turkish
=> [CMT-758-1103] translate(article): ''how-yearn-calculates-estimated-returns'' - TR

public/_posts/_articles/marco-worms/yearn-finance-explained-what-are-vaults-and-strategies/tr.md
This pull request is translated yearn-finance-explained-what-are-vaults-and-strategies to turkish
=> [CMT-765-1110] translate(article): ''yearn-finance-explained" - TR

public/_posts/_announcements/update-bowswap-finance/tr.md, public/_posts/_announcements/zero-knowledge-podcast/tr.md, public/_posts/_articles/wot-is-goin-on/yearn-dai-vault/tr.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-53/tr.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-54/tr.md, public/_posts/_tweets/risk-tooling-insight/tr.md, public/_posts/_tweets/what-is-a-DAO/tr.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-755-1100] fix: multiple title translations and duplicates

public/_posts/_articles/marco-worms/partners/tr.md
This pull request is about translated partners article to turkish
=> [CMT-779-1126] translate(article): ''yearn-partners" - TR

public/_posts/_newsletters/Yearn-Finance-Newsletter-58/fr.md
add [French] translation of the [Newsletter] 58
=> translate(newsletter): YN58 - FR

public/_posts/_newsletters/Yearn-Finance-Newsletter-58/tr.md
This pull request is translated Yearn-Finance-Newsletter-58 to turkish
=> [CMT-783-1132] translate(newsletter): ''Yearn-Finance-Newsletter-58 " - TR

pages/[path]/[...slug].js, pages/[path]/index.js, pages/index.js
Add the support for the new `kish` subfolder in articles
Should fix #1079
*NA*
=> [CMT-799-1150] feat: add kish subfolder support

public/_posts/_articles/kish/my-first-impressions-at-yearn/tr.md
This pull request  is translated my-first-impressions-at-yearn to turkish
=> [CMT-769-1114] translate(article): ''my-first-impressions-at-yearn" - TR

public/_posts/_articles/kish/my-first-impressions-at-yearn/pt.md
Portuguese translation
This pull request translates "My First Impressions at Yearn" into PORTUGUESE
Fixes #(issue)
=> [CMT-771-1118] translate(article): "My First Impressions at Yearn" - PT

public/_posts/_newsletters/Yearn-Finance-Newsletter-58/de.md
This pull request translates YN #58 into GERMAN
Fixes #(issue)
=> [CMT-797-1147] translate(newsletter): "YN #58" - DE

public/_posts/_articles/wot-is-goin-on/yearn-dai-vault/de.md
This pull request translates "Yearn’s Dai Vault" article into GERMAN
Fixes #(issue)
=> translate(article): "Yearn’s Dai Vault" - DE

public/_posts/_articles/marco-worms/diving-into-yearn-metrics/tr.md
This pull request is translated diving-into-yearn-metrics to turkish
=> [CMT-766-1111] translate(article): ''diving-into-yearn-metrics" - TR

public/_posts/_articles/marco-worms/how-new-yearn-vault-strategies-are-endorsed/tr.md
This pull request  is translated how-new-yearn-vault-strategies-are-endorsed to turkish
=> [CMT-767-1112] translate(article): '' how-new-yearn-vault-strategies-are-endorsed" - TR

public/_posts/_articles/yearn-finance/tenderly/tr.md
This pull request is about translated tenderly article to turkish
=> [CMT-759-1104] translate(article): ''Tenderly'' - TR

public/_posts/_newsletters/Yearn-Finance-Newsletter-57/es.md
This pull request fixes the translations on YN 57
=> [CMT-803-1154] Update es.md

components/TemplateArticle.js, next.config.js, pages/_app.js
This pull request add some SEO elements for each articles, replacing the titles and the ogImage with the one provided by the article itself instead of the whole blog ones
Fixes #1143
=> [CMT-801-1152] feat: add seo for article page

public/_posts/_newsletters/Yearn-Finance-Newsletter-58/ja.md
This pull request is translate newsletter into japanese
=> [CMT-798-1149] translation(newsletter): "Yearn Finance Newsletter #58" - JA

public/_posts/_newsletters/Yearn-Finance-Newsletter-55/en.md
Fix the year from 2021 to 2022
This pull request fixes an error
=> [CMT-805-1156] fix(newsletter): 55 - update year - en

public/_posts/_newsletters/Yearn-Finance-Newsletter-41/zh.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-42/zh.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-43/zh.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-44/zh.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-45/zh.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-46/zh.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-47/zh.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-48/zh.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-49/zh.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-54/zh.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-55/zh.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-56/zh.md
This pull request fixes duplicate titles and title translations fix in newsletters - chinese
Fixes #(issue)
=> [CMT-807-1159] fix: duplicate titles and title translations fix in newsletters - chinese

public/_posts/_articles/marco-worms/diving-into-yearn-metrics/es.md
This pull request edits SPANISH translations of "diving-into-yearn-metrics" article
Fixes #(issue)
=> [CMT-823-1175] fix(article): diving-into-yearn-metrics - ES

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-03-07/ja.md
This pull request is translation into japanese
=> [CMT-820-1172] translate(update) : web-engineering-update-mar-7 - JA

public/_posts/_articles/yearn-finance/tenderly/pt.md
This pull request translates tenderly article into PORTUGUESE
Fixes #(issue)
=> [CMT-816-1168] translate(article): "tenderly" - PT

public/_posts/_articles/marco-worms/yearn-partners/pt.md
This pull request translates "yearn-partners" article into PORTUGUESE
Fixes #(issue)
=> [CMT-814-1166] translate(article): "yearn-partners" - PT

public/_posts/_podcasts/podcasts-talks/pt.md
This pull request translates "List of Podcasts and Talks" into PORTUGUESE
Fixes #(issue)
=> [CMT-789-1139] translate(podcast): "List of Podcasts and Talks" - PT

public/_posts/_articles/yearn-finance/clarifying-2020-mergers/pt.md
This pull request translates clarifying-2020-mergers into PORTUGUESE
Fixes #(issue)
=> [CMT-787-1137] translate(article): clarifying-2020-mergers - PT

public/_posts/_tweets/why-is-yearn-finance-built-different/pt.md
This pull request translates why-is-yearn-finance-built-different tweet into PORTUGUESE
Fixes #(issue)
=> [CMT-776-1123] translate(tweet): why-is-yearn-finance-built-different - PT

public/_posts/_articles/marco-worms/yearn-finance-explained-what-are-vaults-and-strategies/pt.md
This pull request translates what-are-vaults-and-strategies into PORTUGUESE
Fixes #(issue)
=> [CMT-775-1122] translate(article): what-are-vaults-and-strategies - PT

public/_posts/_updates/web-team/stealth-safe-guard-mev-protection-for-your-gnosis-safe/pt.md
This pull request translates mev-protection-for-your-gnosis-safe into PORTUGUESE
Fixes #(issue)
=> [CMT-821-1173] translate(engineering): mev-protection-for-your-gnosis-safe - PT

public/_posts/_announcements/deposit-together/pt.md
This pull request translates deposit-together into PORTUGUESE
Fixes #(issue)
=> [CMT-764-1109] translate(announcement): deposit-together - PT

public/_posts/_updates/web-team/2022-01-31/pt.md
This pull request translates web-engineering-update-31-jan into PORTUGUESE
Fixes #(issue)
=> [CMT-763-1108] translate(engineering): web-engineering-update-31-jan - PT

public/_posts/_tweets/what-can-you-do-in-a-DAO/pt.md
Portuguese translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-762-1107] translate(tweet): what-can-you-do-in-a-DAO - PT

public/_posts/_articles/marco-worms/diving-into-yearn-metrics/pt.md
This pull request translates "Diving into Yearn Metrics" article into PORTUGUESE
Fixes #
=> [CMT-678-1015] translate(article): "Diving into Yearn Metrics" - PT

public/_posts/_newsletters/Yearn-Finance-Newsletter-57/vi.md
This pull request add Vi L10n for YN 57
Fixes #
=> [CMT-810-1162] translate(newsletter): YN 57 - VI

public/_posts/_newsletters/Yearn-Finance-Newsletter-41/es.md
This pull request translates YN41 into SPANISH
Fixes #(issue)
=> [CMT-794-1144] translate(newsletter): YN41 - ES

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-03-07/pt.md
PT Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-830-1182] translate(engineering): web-team-update-2022-03-07 - PT

public/_posts/_articles/the-blue-pill/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-802-1153] translate(article): the blue pill - es

public/_posts/_newsletters/Yearn-Finance-Newsletter-56/vi.md
This pull request add Vi L10n for YN 56
Fixes #
=> [CMT-809-1161] translate(newsletter): YN 56 - VI

public/_posts/_articles/andre-cronje/introducing-fixed-forex/de.md
This pull request translates "Introducing fixed forex" article into GERMAN
Fixes #(issue)
=> [CMT-826-1178] translate(article): Introducing fixed forex - DE

public/_posts/_announcements/deposit-together/de.md
This pull request translates Deposit Together into GERMAN
Fixes #(issue)
=> [CMT-825-1177] translate(announcement): Deposit Together - DE

public/_posts/_articles/marco-worms/yearn-finance-explained-what-are-vaults-and-strategies/de.md
This pull request translates What are Vaults and Strategies? article into GERMAN
Fixes #(issue)
=> [CMT-804-1155] translate(article): What are Vaults and Strategies?- DE

public/_posts/_newsletters/Yearn-Finance-Newsletter-57/de.md
This pull request translates "Yearn-Finance-Newsletter-57" into GERMAN
Fixes #1036
=> [CMT-697-1036] translate(newsletter): "Yearn-Finance-Newsletter-57" - DE

public/_posts/_newsletters/Yearn-Finance-Newsletter-54/de.md
This pull request translates YN54 into GERMAN
Fixes #(issue)
=> [CMT-740-1082] translate(newsletter): YN54 - DE

public/_posts/_articles/marco-worms/how-new-yearn-vault-strategies-are-endorsed/de.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-781-1130] translate(article): How new Yearn Vault strategies are endorsed - DE

public/_posts/_newsletters/Yearn-Finance-Newsletter-56/de.md
This pull request translates "Yearn-Finance-Newsletter-56" into GERMAN
Fixes #1035
=> [CMT-696-1035] translate(newsletter): "Yearn-Finance-Newsletter-56" - DE

public/_posts/_newsletters/Yearn-Finance-Newsletter-58/vi.md
This pull request add Vi L10n for YN 58
Fixes #
=> [CMT-811-1163] translate(newsletter): YN 58 - VI

public/_posts/_newsletters/Yearn-Finance-Newsletter-58/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-784-1133] translate(newsletter): "Yearn Finance Newsletter #58" - ES

public/_posts/_announcements/what-do-i-need-to-write-a-strategy/el.md
This pull request is a translation in Greek of the announcement, what do I need to write a strategy.
=> [CMT-841-1194] translate(announcement): what-do-i-need-to-write-a-strategy - EL

public/_posts/_announcements/token-terminal/el.md
This pull request is a Greek translation of the token terminal announcement
=> [CMT-839-1191] translate(announcement): Token terminal - EL

public/_posts/_announcements/updated-YFIstats-dashboards/el.md
This pull request is a Greek translation of the YFIstats Dashboards announcement.
=> [CMT-840-1193] translate(announcement): Update YFIStats Dashboards - EL

public/_posts/_announcements/legal-activism-DAO/el.md
This pull request is a translation of the Proposal Fund Builder First Legal Activism ~DAO~, announcement in Greek
=> [CMT-836-1188] translate(announcement): Legal Activism DAO - EL

public/_posts/_podcasts/podcasts-talks/el.md
Greek Translation of the Podcasts and Talks list.
Fixes #(issue)
=> [CMT-832-1184] translate: podcasts - EL

public/_posts/_announcements/zero-knowledge-podcast/el.md
This pull request is a translation of the Zero Knowledge Podcast in Greek.
* \[Χ\] Add a new translation
=> [CMT-835-1187] translate(announcement): Zero Knowledge Podcast - EL

public/_posts/_announcements/deposit-together/el.md
Greek translation for the deposit together announcement
Fixes #(issue)
=> [CMT-833-1185] translate(announcement): deposit together - EL

public/_posts/_articles/gemini/vi.md
This pull request add Vi L10n for "Yearn Finance and Money Robots"
Fixes #
=> [CMT-812-1164] translate(article): "Yearn Finance and Money Robots" - VI

public/_posts/_articles/marco-worms/how-yearn-calculates-estimated-returns/de.md
This pull request translates "How Yearn calculates estimated returns" article into GERMAN
Fixes #(issue)
=> [CMT-796-1146] translate(article): How Yearn calculates estimated returns (APY) - DE

public/_posts/_articles/andre-cronje/decentralized-payroll-management-for-daos/vi.md
This pull request add Vi L10n for "Decentralized payroll management for DAOs"
Fixes #323
=> [CMT-116] translate(article): "Decentralized payroll management for DAOs" - VI

public/_posts/_newsletters/Yearn-Finance-Newsletter-55/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-792-1142] translate(newsletter): YN55 - ES

public/_posts/_newsletters/Yearn-Finance-Newsletter-54/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-791-1141] translate(newsletter): YN54 - ES

public/_posts/_newsletters/Yearn-Finance-Newsletter-53/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-790-1140] translate(newsletter): YN53 - ES

public/_posts/_announcements/yearn-synthetix-DAO-twitter-space/el.md
This pull request is a translation in Greek of the announcement Yearn & Synthetix DAO twitter space.
=> [CMT-842-1195] Yearn & Synthetix DAO twitter space Greek

localization/hi.json
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-741-1085] Blog home page - Hindi localization suggestion

public/_posts/_articles/kish/my-first-impressions-at-yearn/de.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-780-1127] translate(article): My First Impressions at Yearn - DE

localization/tr.json
This pull request is about translated  localization file
=> [CMT-846-1199] translated localization file

public/_posts/_articles/seba/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-774-1121] translate(article): SEBA Decentralised Asset Management - ES

public/_posts/_articles/marco-worms/setup-notifications-tenderly/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-848-1201] translate(article): setup-notifications-tenderly - ES

public/_posts/_articles/marco-worms/setup-notifications-tenderly/fr.md
add french version of [Article] setup-notifications-tenderly
=> add french version of [Article] setup-notifications-tenderly

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-01-03/pt.md
This pull request translates web-team-update-2022-01-03 into PORTUGUESE
Fixes #(issue)
=> [CMT-852-1206] translate(engineering): web-team-update-2022-01-03 - PT

public/_posts/_articles/marco-worms/setup-notifications-tenderly/pt.md
This pull request translates setup-notifications-tenderly article into PORTUGUESE
Fixes #(issue)
=> [CMT-851-1205] translate(article): setup-notifications-tenderly - PT

public/_posts/_articles/yearn-finance/clarifying-2020-mergers/es.md
This pull request translates Clarifying 2020 Mergers  into SPANISH
Fixes #(issue)
=> [CMT-772-1119] translate(article): Clarifying 2020 Mergers - ES

public/_posts/_announcements/deposit-together/es.md, public/_posts/_articles/forum/what-can-you-do-with-yfi/es.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-46/es.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-48/es.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-49/es.md
This pull request fixes misc typo and formatting fixes
Fixes #(issue)
=> [CMT-855-1209] fix: misc typo and formatting fixes

public/_posts/_newsletters/Yearn-Finance-Newsletter-53/zh.md
This pull request translates YN53 to CHINESE
Fixes #(issue)
=> [CMT-861-1217] translate(newsletter): YN 53 - ZH

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-03-14/ja.md
This pull request is a translation into japanese.
Fixes #(issue)
=> [CMT-862-1218] translation(engineering): web-update-14.03

public/_posts/_articles/the-blue-pill/pt.md
Standardize some pronouns for some concepts, also fixes some typos and some phrases that were a bit off the intent of the original words
=> Update portuguese bluepill translation

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-01-10/pt.md
This pull request translates engineering update 10.01 into PORTUGUESE
Fixes #(issue)
=> [CMT-857-1212] translate(updates): yearn web 01 10 - pt

public/_posts/_announcements/legal-activism-DAO/id.md
reviewed and corrected
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
* \[✅ \] Add a new translation
* \[✅ \] Miss spelling corrected
=> [CMT-868-1225] fix(translation update): legal-activism-dao - ID

public/_posts/_articles/the-blue-pill/es.md
@RestlessMike
added some small changes here and there
=> [CMT-863-1219] edit(article): The Blue Pill - PT

public/_posts/_articles/marco-worms/self-hosting/fr.md
add [french] version  article self-hosting
=> add [french] version  article self-hosting

public/_posts/_articles/the-blue-pill/tr.md
This pull request is about translated The blue pill article
=> [CMT-884-1244] translate(article): ''The Blue Pill" - TR

public/_posts/_financials/quarterly-report/quarterly-report-2021-Q3/tr.md
This pull request  is about translated quarterly-report-2021-Q3 to Turkish
=> [CMT-875-1232] translate(financials): ''quarterly-report-2021-Q3" - TR

public/_posts/_newsletters/Yearn-Finance-Newsletter-44/es.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-47/es.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-53/es.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-54/es.md, public/_posts/_newsletters/Yearn-Finance-Newsletter-55/es.md
Work in progress
DO NOT MERGE YET
=> [CMT-878-1237] edit(newsletters): Spanish translation review

public/_posts/_articles/the-blue-pill/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-877-1236] Update es.md - The Blue Pill

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-01-17/pt.md
PT Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-914-1275] translate(yearn-web-engineering-update-2022-01-17): PT

public/_posts/_tweets/what-is-a-DAO/es.md
=> [CMT-913-1274] Translation : yearn-comms/public/_posts/_tweets/what-is-a-DAO : ES

public/_posts/_tweets/risk-tooling-insight/es.md
=> [CMT-910-1271] translate(tweet): risk-tooling-insight - ES

public/_posts/_newsletters/Yearn-Finance-Newsletter-59/fr.md
=> [CMT-895-1256] translate(newsletter): YN59 - FR

public/_posts/_newsletters/Yearn-Finance-Newsletter-59/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-903-1264] translate(newsletter): YN59 - ES

public/_posts/_newsletters/Yearn-Finance-Newsletter-59/vi.md
This pull request add Vi L10n for YN59
Fixes #
=> [CMT-904-1265] vi L10n for YN59

public/_posts/_newsletters/Yearn-Finance-Newsletter-52/zh.md
translate Newsletter 52 in Chinese
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-902-1263] translation(newsletter): 52 - zh

public/_posts/_newsletters/Yearn-Finance-Newsletter-59/pt.md
PT Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-896-1257] translate(newsletter): YN59 - PT

public/_posts/_newsletters/Yearn-Finance-Newsletter-59/tr.md
This pull request is translated NL 59
=> [CMT-892-1253] translate(newsletter): YN59 - TR

public/_posts/_articles/andre-cronje/introducing-fixed-forex/zh.md
delete I in the title; add 'space' to make it easier for eyes.
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-901-1262] edit-fixed-forex-in-Chinese

public/_posts/_updates/web-team/stealth-safe-guard-mev-protection-for-your-gnosis-safe/tr.md
This pull request  is translated gnosis-safe to turkish
=> [CMT-908-1269] translate(engineering): gnosis-safe - TR

public/_posts/_articles/marco-worms/setup-notifications-tenderly/tr.md
This pull request is translated setup-notifications-tenderly article to turkish
=> [CMT-888-1248] translate: (article) ''setup-notifications-tenderly'' to turkish

public/_posts/_financials/quarterly-report/quarterly-report-2021-Q3/pt.md
PT Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-893-1254] translate(financials): quarterly-report-2021-Q3 - PT

public/_posts/_tweets/why-is-yearn-finance-built-different/en.md, public/_posts/_tweets/why-is-yearn-finance-built-different/pt.md, public/_posts/_tweets/why-is-yearn-finance-built-different/tr.md
This pull request is translated why-is-yearn-finance-built-different twit to turkish
=> [CMT-889-1249] translate(tweet): ''why-is-yearn-finance-built-different'' - TR

public/_posts/_articles/marco-worms/diving-into-yearn-metrics/zh.md
能过 -> 能够
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-900-1261] fix(typo): yearn-metrics article ZH

public/_posts/_tweets/claim-from-old-ygov/es.md
=> [CMT-909-1270] translate(tweet): claim-from-old-ygov - ES

public/_posts/_tweets/what-can-you-do-in-a-DAO/es.md
=> [CMT-911-1272] translate(tweet): what-can-you-do-in-a-DAO - ES

public/_posts/_newsletters/Yearn-Finance-Newsletter-60/en.md
=> [CMT-917-1282] fix: add missing link - YN60

public/_posts/_newsletters/Yearn-Finance-Newsletter-60/fr.md
add [French] version of the 60th[newsletter]
=> translate(newsletter): YN60 - FR

public/_posts/_newsletters/Yearn-Finance-Newsletter-60/tr.md
This pull request is translated NL #60 to turkish
=> [CMT-919-1285] translate(newsletter): YN60 - TR

public/_posts/_newsletters/Yearn-Finance-Newsletter-60/pt.md
PT Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-921-1287] translate(newsletter): YN60 - PT

public/_posts/_newsletters/Yearn-Finance-Newsletter-60/vi.md
This pull request add Vi L10n for YN 60
Fixes #
=> [CMT-922-1288] translate(newsletter): YN60 - VI

public/_posts/_financials/quarterly-report/quarterly-report-2021-Q3/vi.md
This pull request add Vi L10n for Yearn Financial report Q3 2021
Fixes #
=> [CMT-923-1289] translate(financials) Q3-2021-financial-report - VI

public/_posts/_newsletters/Yearn-Finance-Newsletter-60/zh.md
translation check required before the merge.
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-926-1293] translate(newsletter): YN60 - ZH

public/_posts/_tweets/Yearning-for-Yearn/pt.md
PT Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-925-1292] translate(tweet): yearning-for-yearn - PT

public/_posts/_articles/marco-worms/self-hosting/pt.md
PT Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-929-1296] translate(article): self-hosting - PT

public/_posts/_articles/marco-worms/yearn-partners/zh.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-933-1300] TLcheck(article): yearn-partners - ZH

public/_posts/_articles/marco-worms/yearn-governance/fr.md
add [French] version of the "Yearn governance explained: Proposals, $YFI token, and execution"  [Article]
=> translate(article): yearn-governance - FR

public/_posts/_updates/web-team/stealth-safe-guard-mev-protection-for-your-gnosis-safe/es.md
=> [CMT-928-1295] translate(engineering): stealth-safe-guard-mev-protection-for-your-gnosis-safe - ES

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-01-10/es.md
=> [CMT-931-1298] translate(engineering): yearn-web-engineering-update-2022-01-10 - ES

public/_posts/_articles/marco-worms/yearn-partners/es.md
=> [CMT-935-1303] translate(article): yearn-partners - ES

public/_posts/_newsletters/Yearn-Finance-Newsletter-61/en.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-947-1316] fix: broken img links, typos

public/_posts/_newsletters/Yearn-Finance-Newsletter-61/tr.md
This pull request is about translation: nl61 to turkish
=> [CMT-948-1317] translate(newsletter): YN61 - TR

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-01-03/es.md
=> [CMT-930-1297] translate(engineering): yearn-web-engineering-update-2022-01-03 - ES

public/_posts/_articles/marco-worms/yearn-finance-explained-what-are-vaults-and-strategies/es.md
=> [CMT-939-1308] translate(article): what-are-vaults-and-strategies - ES

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-01-31/es.md
=> [CMT-941-1310] translate(engineering): yearn-web-engineering-update-2022-01-31 - ES

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-01-17/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-944-1313] translate(engineering): yearn-web-engineering-update-2022-01-17 - ES

public/_posts/_newsletters/Yearn-Finance-Newsletter-61/fr.md
add french version for [Newsletter] 61
=> add french version for [Newsletter] 61

public/_posts/_newsletters/Yearn-Finance-Newsletter-61/pt.md
PT Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-953-1322] translate(Yearn-Finance-Newsletter-61): PT

public/_posts/_newsletters/Yearn-Finance-Newsletter-61/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-954-1325] Translate(newsletter): - Yearn-Finance-Newsletter-61- ES

public/_posts/_newsletters/Yearn-Finance-Newsletter-61/zh.md
translation check required.
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-955-1326] translate(newsletter): YN61 - ZH

pages/_app.js
This pull request adds support for Plausible analytics
Fixes #282
=> [CMT-982-1355] feat: add support for Plausible analytics

public/_posts/_newsletters/Yearn-Finance-Newsletter-61/de.md
This pull request adds YN61 translation into German
Fixes #(issue)
=> [CMT-963-1336] translate(german): YN61 (newsletter)

public/_posts/_newsletters/Yearn-Finance-Newsletter-61/vi.md
This pull request add Vi L10n for YN 61
Fixes #
=> [CMT-958-1329] translate(newsletter): YN61 - VI

public/_posts/_articles/people-of-yearn/marcos-worm/tr.md
This pull request  is translatedmarco worms interview to turkish
=> [CMT-997-1373] translate(turkish): people-of-yearn-marco-worms (article)

public/_posts/_articles/people-of-yearn/marcos-worm/pt.md
This pull request translates people-of-yearn-marco-worms article into PORTUGUESE
Fixes #(issue)
=> [CMT-1005-1381] translate(portuguese): people-of-yearn-marco-worms (article)

public/_posts/_articles/people-of-yearn/marcos-worm/fr.md
add FRENCH for people-of-yearn with marcos-worm
=> [CMT-1002-1378] translate(french): people-of-yearn-marco-worms (article)

public/_posts/_articles/people-of-yearn/marcos-worm/es.md
This pull request translates the people-of-yearn-marco-worms article into SPANISH
Fixes #(issue)
=> [CMT-992-1366] translate(spanish): people-of-yearn-marco-worms (article)

public/_posts/_articles/people-of-yearn/RestlessMik3/es.md
=> [CMT-962-1334] translate(spanish): people-of-yearn-RestlessMik3 (article)

public/_posts/_articles/people-of-yearn/RestlessMik3/pt.md
This pull request translates people-of-yearn-RestlessMik3 article into PORTUGUESE
Fixes #(issue)
=> [CMT-999-1375] translate(portuguese): people-of-yearn-RestlessMik3 (article)

public/_posts/_articles/people-of-yearn/RestlessMik3/tr.md
This pull request is translated restless interview to turkish
=> [CMT-1000-1376] translate(turkish): people-of-yearn-RestlessMik3 (article)

public/_posts/_articles/people-of-yearn/Jyhelper/pt.md
This pull request translates people-of-yearn-Jyhelper  article into PORTUGUESE
Fixes #(issue)
=> [CMT-996-1372] translate(portuguese): people-of-yearn-Jyhelper (article)

public/_posts/_articles/people-of-yearn/Jyhelper/es.md
This pull request translates people-of-yearn-Jyhelper  article into SPANISH
Fixes #(issue)
=> [CMT-961-1333] translate(spanish): people-of-yearn-Jyhelper (article)

public/_posts/_tweets/ERC-4626s/pt.md
This pull request is translated erc4626 tweet to PORTUGUESE
=> [CMT-1009-1385] translate(portuguese): ERC-4626s (tweet)

public/_posts/_tweets/ERC-4626s/tr.md
This pull request is translated erc4626 tweet to turkish
=> [CMT-988-1361] translate(turkish): ERC4626s (tweet)

public/_posts/_articles/marco-worms/yearn-governance/zh.md
This pull request translates yearn-governance article into CHINESE
Fixes #(issue)
=> [CMT-960-1332] translate(chinese): yearn-governance (article)

public/_posts/_articles/marco-worms/yearn-governance/tr.md
This pull request is translated yearn gov to turkish
Fixes #(issue)
=> [CMT-983-1356] translate(turkish): yearn-governance (article)

public/_posts/_updates/yearn-allowlist/en.md
change adresse, after Marco's comment (see on TG)
=> [CMT-1025-1404] fix(typo): replace line - eth address

public/_posts/_articles/yearn-finance/yearn-wants-to-buy-your-YFI/es.md
This pull request translates yearn-wants-to-buy-your-YFI article into SPANISH
Fixes #(issue)
=> [CMT-1037-1416] translate(spanish): yearn-wants-to-buy-your-YFI (article)

public/_posts/_articles/yearn-finance/yearn-wants-to-buy-your-YFI/tr.md
This pull request translated yearn-wants-to-buy-your-YFI article to turkish
=> [CMT-1036-1415] translate(turkish): yearn-wants-to-buy-your-YFI (article)

public/_posts/_updates/yearn-allowlist/pt.md
This pull request translates yearn-allowlist eng. article into PORTUGUESE
Fixes #(issue)
=> [CMT-1028-1407] translate(portuguese): yearn-allowlist (engineering)

public/_posts/_updates/yearn-allowlist/tr.md
This pull request translates yearn-allowlist eng. article into TURKISH
Fixes #(issue)
=> [CMT-1013-1389] translate(turkish): yearn-allowlist (engineering)

public/_posts/_articles/yearn-finance/yearn-wants-to-buy-your-YFI/zh.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-1038-1417] translate(chinese): yearn-wants-to-buy-your-YFI (article)

public/_posts/_articles/yearn-finance/clarifying-2020-mergers/de.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-977-1350] translate(german): clarifying-2020-merger (article)

public/_posts/_articles/marco-worms/yearn-partners/de.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-1001-1377] translate(german): yearn-partners (article)

public/_posts/_articles/marco-worms/yearn-governance/pt.md
Pt Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-994-1370] translate(portuguese): yearn-governance (article)

public/_posts/_newsletters/Yearn-Finance-Newsletter-61/zh.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-1012-1388] tl-check(chinese): YN61 (newsletter)

public/_posts/_articles/farrahmay/yearn-at-eth-amsterdam/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-1040-1419] translate(spanish): yearn-at-eth-amsterdam (article)

public/_posts/_articles/marco-worms/yearn-v3/en.md, public/_posts/_articles/marco-worms/yearn-v3/tr.md
v3 article translated to turkish
=> [CMT-987-1360] translate(turkish): yearn-v3 (article)

public/_posts/_articles/marco-worms/yearn-v3/fr.md
add french version of the article yearn-v3
=> translate(french): yearn-v3 (article)

public/_posts/_articles/marco-worms/yearn-v3/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-993-1369] translate(spanish): yearn-v3 (article)

public/_posts/_articles/marco-worms/yearn-v3/pt.md
PT Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-995-1371] translate(portuguese): yearn-v3 (article)

public/_posts/_articles/marco-worms/yearn-v3/de.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-1030-1409] translate(german): yearn-v3 (article)

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-02-28/tr.md
yearn-web-engineering-update translated to turkish
=> [CMT-986-1359] translate(turkish): web-engineering-update-2022-02-28 (engineering)

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-02-28/pt.md
PT Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-1008-1384] translate(portuguese): yearn-web-engineering-update-2022-02-28 (engineering)

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-02-28/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-1035-1414] translate(spanish): yearn-web-engineering-update-2022-02-28 (engineering)

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-03-14/tr.md
yearn-web-engineering-update translated to turkish
=> [CMT-984-1357] translate(turkish): web-engineering-update-2022-03-14 (engineering)

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-03-07/tr.md
yearn-web-engineering-update translated to turkish
=> [CMT-985-1358] translate(turkish): web-engineering-update-2022-03-07 (engineering)

public/_posts/_articles/marco-worms/diving-into-yearn-metrics/de.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-859-1215] translate(german): diving-into-yearn-metrics (article)

public/_posts/_tweets/ERC-4626s/fr.md
Translation of the tweet about ERC-4626
=> [CMT-1043-1422] translate(french): ERC-4626s (tweet)

public/_posts/_tweets/Yearning-for-Yearn/zh.md
translation check required.
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-979-1352] translate(chinese): yearning-for-yearn (tweet)

public/_posts/_tweets/Yearning-for-Yearn/tr.md
This pull request is translated yearning for yearn tweet to turkish
=> [CMT-989-1362] translate(turkish): yearning-for-yearn (tweet)

public/_posts/_articles/marco-worms/setup-notifications-tenderly/de.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-980-1353] translate(german): setup-tenderly-notifications (article)

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-02-21/tr.md
This pull request  is translated engineering updates - 21 feb in turkish
=> [CMT-1033-1412] translate(turkish): engineering updates - 21 feb

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-01-31/tr.md
This pull request  is translated engineering updates - 31jan in turkish
=> [CMT-1034-1413] translate(turkish): engineering update - 31jan

public/_posts/_newsletters/Yearn-Finance-Newsletter-45/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-991-1365] translate(spanish): YN45 (newsletter)

public/_posts/_articles/transcriptions/how-to-contribute-to-daos/tr.md
This pull request is translated article how to contribute in a dao to turkish
=> [CMT-1010-1386] translate(turkish): how-to-contribute-to-daos (transcriptions)

public/_posts/_articles/marco-worms/self-hosting/en.md, public/_posts/_articles/marco-worms/self-hosting/es.md, public/_posts/_articles/marco-worms/self-hosting/fr.md, public/_posts/_articles/marco-worms/self-hosting/hi.md, public/_posts/_articles/marco-worms/self-hosting/pt.md, public/_posts/_articles/marco-worms/self-hosting/tr.md, public/_posts/_articles/marco-worms/self-hosting/zh.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-1042-1421] translate(spanish): self-hosting-web3-services (article)

public/_posts/_updates/web-team/yearn-web-engineering-update-2022-02-21/en.md, public/_posts/_updates/web-team/yearn-web-engineering-update-2022-02-21/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-1029-1408] translate(spanish) : web-engineering-update-2022-02-21 (engineering)

public/_posts/_updates/yearn-allowlist/zh.md
correct some typo 交益-交易;\
small translation check.
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-1039-1418] TLcheck(chinese): yearn-allowlist (article)

public/_posts/_newsletters/Yearn-Finance-Newsletter-62/tr.md
This pull request translated newsletter#62 to turkish
=> [CMT-1061-1440] translate (newsletter) : nl # 62 to tr

public/_posts/_newsletters/Yearn-Finance-Newsletter-62/es.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-1059-1438] translate:(newsletter): newsletter 62: ES

public/_posts/_newsletters/Yearn-Finance-Newsletter-62/de.md
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-1064-1443] YN #62 German Translation

public/_posts/_articles/farrahmay/hacking-with-yearn/pt.md
PT Translation
>
> ```
> fix #1 #2 #3
> ```
Fixes #(issue)
=> [CMT-1056-1435] translate(Portuguese): hacking-with-yearn(article)

public/_posts/_articles/draper/justin-trudeau/fr.md
=> translate(french): how-justin-trudeau-helped-create-the-latest-yearn-campaign (article)

public/_posts/_articles/marco-worms/where-does-yield-comes-from/fr.md
add french translation for where-does-yield-comes-from
=> translate(french): where-does-yield-come-from (article)

public/_posts/_articles/draper/rebranding-yearn/fr.md
add translate(french): where-does-yield-come-from (article)
https://blog.yearn.finance/articles/draper/rebranding-yearn
=> translate(french): rebranding-yearn (article)

public/_posts/_articles/marco-worms/subgraph-explained/fr.md
add french for article about subgraphs by Marcos
https://blog.yearn.finance/articles/marco-worms/subgraph-explained
=> translate(french): subgraph-explained (article)

public/_posts/_articles/draper/hackathon/en.md, public/_posts/_articles/draper/hackathon/fr.md
translate(french):  yearn-x-ethonline-hackathon (article)
https://medium.com/iearn/yearn-x-ethonline-hackathon-832768bc2842
=>  translate(french):  yearn-x-ethonline-hackathon (article)

public/_posts/_articles/marco-worms/yearn-vault-tokens-as-collateral/fr.md
translate(french): Yearn Vault Tokens as collateral (article) by MArco 
Fixes #(issue)
https://blog.yearn.finance/articles/marco-worms/yearn-vault-tokens-as-collateral
=> translate(french): yearn-vault-tokens-as-collateral (article)

public/_posts/_articles/yearn-finance/cowswap/fr.md
Translation of yearn-cowswap (article)
https://blog.yearn.finance/articles/yearn-finance/cowswap
=> translate(french): yearn-cowswap (article)
